import re

old_dirs = {
"01-central-square": "CENTRAL_SQUARE",
"02-cloud-hill": "CLOUD_HILL",
"03-kikos-home": "KIKOS_HOME",
"04-sun-hill": "SUN_HILL",
"05-mimis-burrow": "MIMIS_BURROW",
"06-opas-tree": "OPA_TREE",
"07-tillos-garden": "TILLOS_GARDEN",
"08-lulus-greenhouse": "LULUS_GREENHOUSE",
"09-poppys-bakery": "POPPYS_BAKERY",
"10-bennys-playground": "BENNYS_PLAYGROUND",
"11-tillos-treehouse": "TILLOS_TREEHOUSE",
"12-milos-pond": "MILOS_POND",
"13-rosies-rose-garden": "ROSIES_ROSE_GARDEN",
"14-lilys-lavender-farm": "LILYS_LAVENDER_FARM",
"15-rainbow-bridge": "RAINBOW_BRIDGE",
"16-friendship-meadow": "FRIENDSHIP_MEADOW",
"17-butterfly-meadow": "BUTTERFLY_MEADOW",
"18-little-forest": "LITTLE_FOREST",
"19-rainbow-creek": "RAINBOW_CREEK",
"20-wish-pond": "WISH_POND",
"21-camping-grove": "CAMPING_GROVE",
"22-story-circle": "STORY_CIRCLE",
"23-art-corner": "ART_CORNER",
"24-adventure-trail": "ADVENTURE_TRAIL",
"25-flower-hill": "FLOWER_HILL",
"26-tree-hill": "TREE_HILL",
"27-stone-hill": "STONE_HILL",
"28-paddle-cove": "PADDLE_COVE",
"29-pony-meadow": "PONY_MEADOW",
"30-hobby-horse-trail": "HOBBY_HORSE_TRAIL",
"31-learning-room": "LEARNING_ROOM",
}
for old, world in old_dirs.items():
    print(f"02-WORLDS/{old}|POMPOM_HILLS_PRODUCTION/02_WORLDS/{world}")
